language: rust

rust: stable

env:
  global:
    - RUST_BACKTRACE=full

matrix:
  include:
    - dist: xenial
      env: RUSTUP_HOST=x86_64-unknown-linux-gnu
    - os: osx
      env: RUSTUP_HOST=x86_64-apple-darwin
    - os: windows
      env: RUSTUP_HOST=x86_64-pc-windows-msvc
    - os: windows
      env: RUSTUP_HOST=x86_64-pc-windows-gnu

install:
  - rustup self update
  - rustup set default-host "$RUSTUP_HOST"
  - rustup update "$TRAVIS_RUST_VERSION"
  - rustup component add clippy rustfmt
  - rustc --version --verbose
  - cargo --version --verbose
  - cargo clippy --version
  - rustfmt --version

script:
  - cargo fmt --all -- --check
  - cargo clippy --all --all-targets -- -D warnings

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  only:
    - master
