[package]
name = "cargo-unused"
version = "0.0.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
description = "Find unused crates."
repository = "https://github.com/qryxip/cargo-unused"
readme = "README.md"
keywords = ["cargo"]
categories = ["development-tools::cargo-plugins"]
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
atty = "0.2.13"
cargo_metadata = "0.8.2"
combine = "3.8.1"
derive_more = "0.15.0"
either = "1.5.2"
env_logger = "0.6.2"
failure = "0.1.5"
filetime = "0.2.7"
fixedbitset = "0.1.9"
fs_extra = "1.1.0"
fs2 = "0.4.3"
futures01 = "0.1.28"
if_chain = "1.0.0"
indexmap = { version = "1.1.0", features = ["serde-1"] }
itertools = "0.8.0"
log = "0.4.8"
maplit = "1.0.2"
miniserde = "0.1.12"
once_cell = "0.2.7"
regex = "1.2.1"
remove_dir_all = "0.5.2"
semver = "0.9.0"
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
shell-escape = "0.1.4"
smallvec = "0.6.10"
structopt = "0.3"
strum = { git = "https://github.com/Peternator7/strum", rev = "00397fe0a31687b7373db15d521a451f201e85f2", features = ["derive"] }
termcolor = "1.0.5"
tokio = { version = "0.1.22", default_features = false, features = ["io", "fs", "rt-full"] }
tokio-process = "0.2.4"
tokio-signal = "0.2.7"
toml = "0.5.3"
